Feat/dynamo db support
authorizerdev/authorizer pull request #262
Opened 2022-10-05 10:45 UTC by manojown

#### What does this PR do?
 DynamoDb Support

#### Env Required
There is few ways we can connect dynamodb with our app

1. AWS credentials config - if this setup is already done then wont need to specify any key in env,  require to pass `REGION`
2. Manually Pass the `AWS_ACCESS_KEY` , `AWS_SECRET_KEY` and `REGION` in env file.
3. Local setup - In Local setup needed to pass `DATABASE_URL` and `REGION` which suppose to be you `http://localhost:port` ( default port : 8000 ).

#### If this PR affects any API reference documentation, please share the updated endpoint references
Note - In other DB's indices prevent the duplication in table but in dynamodb it's not the case so have to take care of duplication by our self.

#### Local testing tools can help
`https://github.com/aaronshaf/dynamodb-admin` -  helps in investigate the data, meta and manual crud operation.

2022-10-08 10:09 UTC, lakhansamani commented
@manojown there are some merge conflicts that need to be resolved.

2022-10-08 10:50 UTC, manojown commented
here is one small-check, 

> @manojown there are some merge conflicts that need to be resolved.

Done @lakhansamani

2022-10-08 11:00 UTC, lakhansamani requested changes
Requested some changes
Plus we need to add env vars to our persistent store, by adding them here
https://github.com/authorizerdev/authorizer/blob/main/server/env/env.go

2022-10-08 17:42 UTC, manojown commented on server/memorystore/required_env_store.go
> +	REGION             string `json:"REGION"`
sure, as per the discussion going to remove this changes as it's specific to dynamo only.

2022-10-08 18:04 UTC, manojown commented
> Requested some changes Plus we need to add env vars to our persistent store, by adding them here https://github.com/authorizerdev/authorizer/blob/main/server/env/env.go
 
 @lakhansamani AWS_SECRET and AWS_ACCESS keys should be confidential, is this good idea to keep in persistent store? Region we can definitely add in persistent.  
 
WYT ?

2022-10-08 18:26 UTC, lakhansamani commented
We also store other secrets in encrypted format so nothing wrong it. Only one change we need to make is encrypt redis store data and I am working on it

2022-10-08 18:59 UTC, manojown commented
@lakhansamani what if user not specify any key's and wanted to load credentials from aws config ? 
should we force user to add keys in env ?

2022-10-09 08:49 UTC, lakhansamani commented
Got it sure, we can allow user to load from aws config

2022-10-09 08:50 UTC, lakhansamani commented
@manojown is this ready for review?
In that case you move from draft -> ready for review

2022-10-09 08:53 UTC, manojown commented
@lakhansamani yes.

2022-10-13 08:54 UTC, manojMeesho commented
> Requested some changes Plus we need to add env vars to our persistent store, by adding them here https://github.com/authorizerdev/authorizer/blob/main/server/env/env.go

@lakhansamani This comment is resolved right but it still appeared as pending.

2022-10-13 08:59 UTC, manojown commented
> Requested some changes Plus we need to add env vars to our persistent store, by adding them here https://github.com/authorizerdev/authorizer/blob/main/server/env/env.go

@lakhansamani this comment is resolve right, but it still appeared as pending.

2022-10-14 04:11 UTC, lakhansamani commented
Yes, it's resolved now.
Merging this on development and will be doing beta release soon.

2022-10-14 04:12 UTC, lakhansamani commented
@manojown thank you for the contribution.
feel free to take fork from development branch for your new db integration.

2022-10-14 04:12 UTC, merged