Feat/totp for signup
authorizerdev/authorizer pull request #436
Opened 2023-12-06 10:40 UTC by scaletech-milan

#### What does this PR do?
- Added the Signup for TOTP while MFA is enabled.
- Created test cases for email verification and Totp signup.

#### Which issue(s) does this PR fix?
#418 

#### If this PR affects any API reference documentation, please share the updated endpoint references

2023-12-21 20:06 UTC, lakhansamani requested changes
Minor change required

2023-12-21 20:06 UTC, lakhansamani commented on server/resolvers/verify_email.go
> +	isMailOTPDisabled, err := memorystore.Provider.GetBoolStoreEnvVariable(constants.EnvKeyDisableMailOTPLogin)
This check is not required

2024-01-02 06:49 UTC, scaletech-milan commented on server/resolvers/verify_email.go
> +	isMailOTPDisabled, err := memorystore.Provider.GetBoolStoreEnvVariable(constants.EnvKeyDisableMailOTPLogin)
Removed

2024-01-19 15:56 UTC, lakhansamani approved these changes

2024-01-19 15:56 UTC, merged